version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data:cached
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
  web: &app
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node-data:/app/node_modules
      - /app/.git
    environment:
      HOME: /app
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: webpacker
    ports:
      - "3000:3000"
    tty: true
    links:
      - db
  webpacker:
    <<: *app
    command: bin/webpack-dev-server
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - "3035:3035"
    links: []

volumes:
  bundle:
    driver: local
  data:
    driver: local
  node-data:
      driver: local
