# config/application.yml
defaults: &defaults
  uri: none
  http:
    success: '200'
  account:
    line:
      bot_name: ぱっぷん
    google:
      uri:
        book_search:  https://www.googleapis.com/books/v1/volumes
        place_search: https://maps.googleapis.com/maps/api/place/nearbysearch/json
        youtube_search: https://www.googleapis.com/youtube/v3/search
    livedoor:
      weather:
        uri: http://weather.livedoor.com/forecast/webservice/json/v1
    topuru:
      uri: https://pappen.herokuapp.com/events/%s
    expenditure:
      uri: https://pappen.herokuapp.com/line_users/%s/expenditures
    house:
      uri: https://pappen.herokuapp.com/houses/%s
    a3rt:
      uri:
        talk: https://api.a3rt.recruit-tech.co.jp/talk/v1/smalltalk
    gogogs:
      uri: https://gogo.gs/%s
    exchangerates:
      uri: https://api.exchangeratesapi.io/latest
  maxim:
    category:
      movie: 映画
      anime: 漫画・アニメ
      novel: 小説
      hero:  偉人
      joke:  迷言
      other: その他

  prefectures:
    - 北海道
    - 青森県
    - 岩手県
    - 宮城県
    - 秋田県
    - 山形県
    - 福島県
    - 茨城県
    - 栃木県
    - 群馬県
    - 埼玉県
    - 千葉県
    - 東京都
    - 神奈川県
    - 新潟県
    - 富山県
    - 石川県
    - 福井県
    - 山梨県
    - 長野県
    - 岐阜県
    - 静岡県
    - 愛知県
    - 三重県
    - 滋賀県
    - 京都府
    - 大阪府
    - 兵庫県
    - 奈良県
    - 和歌山県
    - 鳥取県
    - 島根県
    - 岡山県
    - 広島県
    - 山口県
    - 徳島県
    - 香川県
    - 愛媛県
    - 高知県
    - 福岡県
    - 佐賀県
    - 長崎県
    - 熊本県
    - 大分県
    - 宮崎県
    - 鹿児島県
    - 沖縄県

  currency:
    JPY: "日本円"
    USD: "USドル"
    EUR: "ユーロ"
    HKD: "香港ドル"
    CNY: "人民元"
    KRW: "韓国ウォン"
    THB: "タイ・バーツ"
    AUD: "オーストラリア・ドル"
    CAD: "カナダ・ドル"
    CHF: "スイス・フラン"
    DKK: "デンマーク・クローネ"
    GBP: "UKポンド"
    NOK: "ノルウェー・クローネ"
    NZD: "ニュージーランド・ドル"
    SEK: "スウェーデン・クローネ"
    SGD: "シンガポール・ドル"
    XPF: "タヒチ・フラン"
    ZAR: "南アフリカ共和国・ランド"
    AED: "UAE・ディルハム"
    BBD: "バルバドス・ドル"
    BDT: "バングラディッシュ・タカ"
    BGN: "ブルガリア・レフ"
    BHD: "バーレーン・ディナール"
    BMD: "バミューダ・ドル"
    BND: "ブルネイ・リンギット"
    BRL: "ブラジル・レアル"
    BSD: "バハマ・ドル"
    CZK: "チェコ・コルナ"
    EGP: "エジプト・ポンド"
    ETB: "エチオピア・ビル"
    FJD: "フィジー・ドル"
    HRK: "クロアチア・クナ"
    HUF: "ハンガリー・フォリント"
    IDR: "インドネシア・ルピア"
    ILS: "イスラエル・新シケル"
    INR: "インド・ルピー"
    JMD: "ジャマイカ・ドル"
    JOD: "ヨルダン・ディナール"
    KWD: "クウェート・ディナール"
    LBP: "レバノン・ポンド"
    LKR: "スリランカ・ルピー"
    MAD: "モロッコ・ディルハム"
    MUR: "モーリシャス・ルピー"
    MWK: "マラウイ・クワチャ"
    MYR: "マレーシア・リンギット"
    NAD: "ナミビア・ドル"
    NGN: "ナイジェリア・ナリア"
    NPR: "ネパール・ルピー"
    OMR: "オマーン・リアル"
    PGK: "パプワニューギニア・キナ"
    PHP: "フィリピン・ペソ"
    PLN: "ポーランド・ズウォティ"
    QAR: "カタール・リアル"
    RON: "ルーマニア・レウ"
    SAR: "サウディ・リヤル"
    SBD: "ソロモン諸島・ドル"
    TND: "チュニジア・ディナール"
    TOP: "トンガ王国・パ・アンガ"
    TRY: "トルコ・リラ"
    TTD: "トリニダード・トバゴ・ドル"
    TWD: "台湾ドル"
    VND: "ベトナム・ドン"
    VUV: "バヌアツ共和国・バツ"
    WST: "サモア・ドル"
    XAF: "中央アフリカ・フラン"
    XCD: "東カリブ・ドル"
    XOF: "ギニアビサウ・フラン"
    ZMW: "ザンビア・クワチャ"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
