# config/application.yml
defaults: &defaults
  uri: none
  http:
    success: '200'
  account:
    line:
      bot_name: ぱっぷん
    google:
      books:
        uri: https://www.googleapis.com/books/v1/volumes
      place:
        uri: https://maps.googleapis.com/maps/api/place/nearbysearch/json
      youtube:
        search_uri: https://www.googleapis.com/youtube/v3/search
        video_uri:  https://www.youtube.com/watch
    livedoor:
      weather:
        uri: http://weather.livedoor.com/forecast/webservice/json/v1
  maxim:
    category:
      movie: 映画
      anime: 漫画・アニメ
      novel: 小説
      hero:  偉人
      joke:  迷言
      other: その他

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
