# config/application.yml
defaults: &defaults
  uri: none
  http:
    success: '200'
  account:
    line:
      bot_name: ぱっぷん
    google:
      uri:
        book_search:  https://www.googleapis.com/books/v1/volumes
        place_search: https://maps.googleapis.com/maps/api/place/nearbysearch/json
        youtube_search: https://www.googleapis.com/youtube/v3/search
    livedoor:
      weather:
        uri: http://weather.livedoor.com/forecast/webservice/json/v1
    topuru:
      uri:
        create:   https://pappen.herokuapp.com/events/new?rmid=%s
        show:     https://pappen.herokuapp.com/events/%s
        expenses: https://pappen.herokuapp.com/expenses/new?event_id=%s
    expenditure:
      uri:
        create: https://pappen.herokuapp.com/expenditure/new/%s
        index:  https://pappen.herokuapp.com/expenditures/%s
  maxim:
    category:
      movie: 映画
      anime: 漫画・アニメ
      novel: 小説
      hero:  偉人
      joke:  迷言
      other: その他

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
