# config/application.yml
defaults: &defaults
  uri: none
  http:
    success: '200'
  account:
    twitter:
      consumer_key: qgqIthjaYksWlnGnq2qnzmoR8
      consumer_secret: 4jEg9lXeQIaQ2d0a3rj4Fpq1smfIP4A11fvlScPIyUjI8qi3ed
      access_token: 1409974286-ytqOPo4kx9UJJhJfz2iGNZRG2DUP0sK84tLPd1B
      access_token_secret: kkx29h4JgwYi9Br08LOY6B2PjoyhSdvlUi5bbSttI9aD4
  maxim:
    category:
      movie: 映画
      anime: 漫画・アニメ
      novel: 小説
      hero:  偉人
      other: その他

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
