# config/application.yml
defaults: &defaults
  uri: none
  http:
    success: '200'
  account:
    twitter:
      consumer_key: j5Vd0WdhoBFhxLTsMysxj3OQ8
      consumer_secret: NqwB6tgqvJiRQ2kGrDAFyuTJZ2qTcUr85Dtoxw0Dwfrnp8hxJG
      access_token: 905725360901316609-yZwg0bkkYRnMMPk8L8FRTSMbWu8NCzf
      access_token_secret: 	1zcgCJEBGeXdPRhUenPEKUZGiYCkiyGdKwZNoVcegSm1e
  maxim:
    category:
      movie: 映画
      anime: 漫画・アニメ
      novel: 小説
      hero:  偉人
      other: その他

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
