# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6b52a5a9fd795cc4d1a26894d95b3fec4de4b7eb20e9fb5b4bdaf7d1abe396a7bf2f8a19c566940373304946de26065eb912736ca2002b86d907fc7d7b395d0f

test:
  secret_key_base: d54a96394a9cf710ca5e0bd160eed3d1f7f52bb0be89498841df3393e91ebba2a5076639fbc94c61d8bafcd85f93751c12e76b3cc53b0dc16544dfa8ac67bac5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
